### ISSUE TITLE
Sensor code improvements/questions

### ISSUE THREAD

**Issue by denilsonsa** [aex351/home-assistant-neerslag-card#1]
Hi! I have a few suggestions/questions:

1. Any reason why using [`command_line`](https://www.home-assistant.io/integrations/sensor.command_line/) instead of [`rest`](https://www.home-assistant.io/integrations/rest)?
    * I assume buienalarm would work fine with REST, as it returns a nicely formatted JSON.
    * I also believe plaintext would work fine with REST as well. By [looking at the code](https://github.com/home-assistant/core/blob/2021.3.4/homeassistant/components/rest/sensor.py#L148-L182), if neither `json_attributes` nor `value_template` is passed, then it looks like the raw response is stored in the template.
2. Any reason why the main data is inside the `data` attribute of the entity? Why not in the main entity state?
3. You can use `{{ state_attr('zone.home', 'latitude') | round(3) }}` and `{{ state_attr('zone.home', 'longitude') | round(3) }}` to automatically populate lat/lon from HA configuration.
    * [Templating is allowed in the command line](https://www.home-assistant.io/integrations/sensor.command_line/#usage-of-templating-in-command)
    * [Templating is also allowed in REST](https://www.home-assistant.io/integrations/rest#resource_template)
4. For the `c` parameter, you can use either `{{ as_timestamp(now()} }}` or [`{{ range(0,999999999)|random }}`](https://www.home-assistant.io/integrations/template/#updating-templates-using-random)

**Comment by denilsonsa** [comment]
Oh, I see why you store everything in an attribute…

```yaml
  - platform: rest
    name: Buienalarm regen data
    resource_template: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat={{ state_attr('zone.home', 'latitude') | round(3) }}&lon={{ state_attr('zone.home', 'longitude') | round(3) }}&region=nl&unit=mm%2Fu&c={{ as_timestamp(now()) }}
    scan_interval: 300
  - platform: rest
    name: Buienradar regen data
    resource_template: https://gpsgadget.buienradar.nl/data/raintext?lat={{ state_attr('zone.home', 'latitude') | round(3) }}&lon={{ state_attr('zone.home', 'longitude') | round(3) }}&c={{ as_timestamp(now()) }}
    scan_interval: 300
```

> State max length is 255 characters.

That's why you store things as an attribute. But since that requires `json_attributes` key, you had to use custom Python code to wrap everything into a trivial JSON.

Still, using templates for the lat/lon and for the random might make the code simpler.
