### ISSUE TITLE
Command Line YAML configuration has moved

### ISSUE THREAD

**Issue by bart1604** [aex351/home-assistant-neerslag-card#38]
Please fix this:

![1](https://github.com/aex351/home-assistant-neerslag-card/assets/42722572/96d016b0-dc56-42d4-a4f0-522db1989f3d)

**Comment by Voxxie** [comment]
Hi @bart1604,

I changed it to: 

```yaml
command_line:
  - sensor:
      name: Neerslag_Buienalarm_Regen_Data
      command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=<lat-2-decimals>&lon=<lon-2-decimals>&region=nl&unit=mm%2Fu&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":'+dataRequest+'}';    print(data);"
      json_attributes:
      - data
      value_template: "last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}"
      scan_interval: 240  
   - sensor:
      name: Neerslag_Buienradar_Regen_Data
      command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=<lat-2-decimals>&lon=<lon-2-decimals>&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    print(data);"
      json_attributes:
      - data
      value_template: "last_changed: {{states.sensor.neerslag_buienradar_regen_data.last_changed}}"
      scan_interval: 240 
```

 * Replace `<lat-2-decimals>` with your latitude. For example: `55.00`
 * Replace `<lon-2-decimals>` with your longitude. For example: `5.00`

**Comment by bart1604** [comment]
Great! will do the same. 

Thanks for the reply.

Now only the installation guide needs to be editted.

**Comment by huizebruin** [comment]
And the other for home zone .

``` 
command_line:
  - sensor:
      name: Neerslag_Buienalarm_Regen_Data
      command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat={{state_attr("zone.home", "latitude") | round(3, default="not available")}}&lon={{state_attr("zone.home", "longitude") | round(3, default="not available")}}&region=nl&unit=mm%2Fu&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":'+dataRequest+'}';    print(data);"
      json_attributes:
      - data
      value_template: "last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}"
      scan_interval: 240  
  - sensor:
      name: Neerslag_Buienradar_Regen_Data
      command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat={{state_attr("zone.home", "latitude") | round(2, default="not available")}}&lon={{state_attr("zone.home", "longitude") | round(2, default="not available")}}&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    print(data);"
      json_attributes:
      - data
      value_template: "last_changed: {{states.sensor.neerslag_buienradar_regen_data.last_changed}}"
      scan_interval: 240 
```
