### ISSUE TITLE
No data from Buienradar

### ISSUE THREAD

**Issue by Dualdriven** [aex351/home-assistant-neerslag-card#41]
First of all, thanks for your time to make this awesome card! I have been using this for 1 week now and it looks great on the dashboard. 

However, I noticed I do not get any data from buienradar, hope you have any ideas.

Things I tried;

1. Clean install through HACS.
2. Re-copied sensor configs
3. Checked if templates for long and lat were returning correct values.
4. Actually setting lon and lat as numbers instead of using the advanced config.
5.  Wondering what could be wrong without coming up with a result.

When I check the gpsgadget.buienradar.nl I do get some raw data which states rainfall at certain times, somehow its just not returned to HA.

Config:
```
  - platform: command_line
    command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat={{state_attr("zone.home", "latitude") | round(3, default="not available")}}&lon={{state_attr("zone.home", "longitude") | round(3, default="not available")}}&region=nl&unit=mm%2Fu&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":'+dataRequest+'}';    print(data);"
    name: Neerslag_Buienalarm_Regen_Data
    json_attributes:
      - data
    value_template: 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed | default(now())}}'
    scan_interval: 240

  - platform: command_line
    command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat={{state_attr("zone.home", "latitude") | round(2, default="not available")}}&lon={{state_attr("zone.home", "longitude") | round(2, default="not available")}}&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    print(data);"
    name: Neerslag_Buienradar_Regen_Data
    json_attributes:
      - data
    value_template: 'last_changed: {{states.sensor.neerslag_buienradar_regen_data.last_changed | default(now())}}'
    scan_interval: 240
```

Current card:
![Neerslag-card1](https://github.com/aex351/home-assistant-neerslag-card/assets/93786489/e3bfbf72-ed5c-4fff-b248-cbcf8f0854a8)

Raw data gpsgadget:
![Neerslag-card buienradar raw data](https://github.com/aex351/home-assistant-neerslag-card/assets/93786489/3d7de401-b39d-4fce-a0a6-26771b1e88ff)

Thanks in advance!
